export const styles = {
  shell: {
    maxWidth: 520,
    margin: '3rem auto',
    padding: '0 1rem',
    fontFamily: 'ui-sans-serif, system-ui, sans-serif',
  },
  appShell: {
    maxWidth: 1100,
    margin: '2rem auto',
    padding: '0 1rem',
    fontFamily: 'ui-sans-serif, system-ui, sans-serif',
    color: 'var(--text)',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '1rem',
    marginBottom: '1rem',
  },
  heading: {
    margin: 0,
  },
  subheading: {
    margin: '0 0 1rem',
    fontSize: '1.1rem',
  },
  workspace: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) minmax(0, 1fr)',
    gap: '1rem',
    marginBottom: '1rem',
  },
  panel: {
    border: '1px solid var(--border)',
    borderRadius: 8,
    padding: '1rem',
    background: 'var(--card)',
  },
  tabs: {
    display: 'flex',
    gap: '0.5rem',
    marginBottom: '1rem',
  },
  form: {
    display: 'grid',
    gap: '0.75rem',
  },
  label: {
    display: 'grid',
    gap: '0.35rem',
    fontSize: '0.9rem',
    fontWeight: 600,
  },
  input: {
    width: '100%',
    boxSizing: 'border-box',
    border: '1px solid var(--border)',
    borderRadius: 6,
    padding: '0.65rem 0.75rem',
    font: 'inherit',
  },
  textarea: {
    width: '100%',
    minHeight: 84,
    boxSizing: 'border-box',
    border: '1px solid var(--border)',
    borderRadius: 6,
    padding: '0.65rem 0.75rem',
    font: 'inherit',
    resize: 'vertical',
  },
  timeGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '0.75rem',
  },
  oauthGrid: {
    display: 'grid',
    gap: '0.5rem',
    marginTop: '1rem',
  },
  activityList: {
    display: 'grid',
    gap: '0.75rem',
  },
  activityItem: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: '1rem',
    border: '1px solid var(--border)',
    borderRadius: 8,
    padding: '0.85rem',
    background: 'var(--card)',
  },
  actions: {
    display: 'flex',
    gap: '0.5rem',
    flexWrap: 'wrap',
  },
  button: {
    border: '1px solid var(--border)',
    borderRadius: 6,
    padding: '0.6rem 0.85rem',
    background: 'var(--card)',
    color: 'var(--text)',
    cursor: 'pointer',
    font: 'inherit',
  },
  activeButton: {
    border: '1px solid var(--text)',
    borderRadius: 6,
    padding: '0.6rem 0.85rem',
    background: 'var(--text)',
    color: 'var(--background)',
    cursor: 'pointer',
    font: 'inherit',
  },
  primaryButton: {
    border: '1px solid var(--primary)',
    borderRadius: 6,
    padding: '0.65rem 0.9rem',
    background: 'var(--primary)',
    color: '#ffffff',
    cursor: 'pointer',
    font: 'inherit',
  },
  dangerButton: {
    border: '1px solid #b42318',
    borderRadius: 6,
    padding: '0.6rem 0.85rem',
    background: 'var(--card)',
    color: '#b42318',
    cursor: 'pointer',
    font: 'inherit',
  },
  smallButton: {
    border: '1px solid',
    borderRadius: 5,
    padding: '0.35rem 0.6rem',
    fontSize: '0.8rem',
    cursor: 'pointer',
    font: 'inherit',
    fontWeight: 500,
  },
  linkButton: {
    border: 'none',
    background: 'none',
    color: '#3538cd',
    cursor: 'pointer',
    font: 'inherit',
    fontSize: '0.85rem',
    padding: 0,
    textDecoration: 'underline',
  },
  badge: {
    display: 'inline-block',
    fontSize: '0.75rem',
    fontWeight: 600,
    padding: '0.2rem 0.55rem',
    borderRadius: 12,
  },
  muted: {
    margin: '0.25rem 0',
    color: '#667085',
  },
  message: {
    border: '1px solid var(--border)',
    borderRadius: 6,
    padding: '0.75rem',
    background: 'var(--card)',
  },
  historyList: {
    marginTop: '0.5rem',
    padding: '0.5rem',
    borderTop: '1px solid var(--border)',
  },
  historyItem: {
    padding: '0.35rem 0',
    fontSize: '0.85rem',
    borderBottom: '1px solid var(--border)',
  },
  modalOverlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(0, 0, 0, 0.4)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
  },
  modal: {
    background: 'var(--card)',
    borderRadius: 16,
    padding: '1.5rem',
    width: '100%',
    maxWidth: 480,
    maxHeight: '90vh',
    overflowY: 'auto',
    boxShadow: '0 10px 40px rgba(0, 0, 0, 0.1)',
  },
};
